name: Setup with Vagrant on Packet
on:
  push:
  pull_request:
    types: [labeled]

jobs:
  vagrant-setup:
    if: contains(github.event.pull_request.labels.*.name, 'ci-check/vagrant-setup')
    runs-on: vagrant
    env:
      TEST_WITH_VAGRANT: "yes"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup state directory
        run: |
          rm -rf ./deploy/state
      - name: Vagrant Test
        run: |
          export VAGRANT_DEFAULT_PROVIDER="virtualbox"
          cd ./test/vagrant
          go test --timeout 1h -v ./
